model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 6
  loss_type: 'H'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000

exp_params:
  dataset: dsprites
  data_path: "../datasets/dsprites"
  img_size: 64
  batch_size: 36 # Better to have a square number
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 10

logging_params:
  save_dir: "logs/"
  name: "BetaVAE_Loss_H_VanillaVAE_dsprites"
  manual_seed: 1265
