model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 1
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000

exp_params:
  dataset: onedim
  data_path: "../datasets/onedim"
  img_size: 64
  batch_size: 36 # Better to have a square number
  num_workers: 8
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: "6,7"
  max_epochs: 20

logging_params:
  save_dir: "logs/"
  name: "BetaVAE_Loss_B_onedim"
  manual_seed: 1265
