model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 6

exp_params:
  dataset: dsprites
  data_path: "../datasets/dsprites"
  img_size: 64
  batch_size: 36 # Better to have a square number
  num_workers: 8
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 10

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE_dsprites"
  manual_seed: 1265
