model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 1

exp_params:
  dataset: onedim
  data_path: "../datasets/onedim"
  img_size: 64
  batch_size: 36 # Better to have a square number
  num_workers: 8
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: "6,7"
  max_epochs: 20

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE_onedim"
  manual_seed: 1265


